[application]

[web.app]

# HTML title tag content
title = "lof-launcher"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "cn.m19"
publisher = "Megatron19"
